# Generated by Django 3.1.1 on 2021-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='class_detail_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
